export enum AuthConst {
    LOG_IN = 'Log in',
    CREATE_AN_ACCOUNT = 'Create an account',
    DO_NOT_HAVE_AN_ACCOUNT = 'Don\'t have an account?',
    NAME = 'Name',
    EMAIL = 'Email',
    PASSWORD = 'Password',
    CONFIRM = 'Confirm',
    CREATE_A_PASSWORD = 'Create a password',
    SELECT_YOUR_GENDER = 'Select your gender',
    SELECT_YOUR_DIFFICULTY = 'Select level of your difficulty?',
    ENTER_NAME_AND_EMAIL = 'Enter your name and email',
    ENTER_WEIGHT_AND_GOAL = 'Enter your current and goal weight',
    ENTER_HEIGHT = 'Enter your height',
    CHOOSE_DATE_BIRTH = 'Choose your date of birth',
    CHOOSE_GOAL_BIRTH = 'Choose goal date',
    WEIGHT = 'Weight',
    GOAL_WEIGHT = 'Goal weight',
    KG = 'kg',
    CM = 'cm',
    DOUBLE_ZERO = '00',
}

export enum AuthException {
    IS_NOT_EMAIL = 'Invalid email address',
    IS_SHORT_EMAIL = 'Email should be greater than 3 characters',
    IS_EMPTY_NAME = 'Enter a name',
    IS_NOT_PASSWORD = 'The length of the password must be between 8 and 12 characters',
    PASSWORD_IS_NOT_EQUAL = 'The password must be equal to the password',
    IS_NOT_POSITIVE_WEIGHT = 'The weight must be greater than zero',
    IS_GOAL_WEIGHT = 'The goal weight must be less than current weight',
    IS_HEIGHT = 'The height must be greater than zero',
    IS_DIFFICULTY = 'Select the difficulty',
    IS_GENDER = 'Select the gender',
    IS_GOAL_DATE = 'Select the goal date',
    IS_BIRTH_DATE = 'Select the birth date',
}